name: Frontend-testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello world
        run: echo "Hello world"
        shell: bash

  good-bye:
    runs-on: ubuntu-latest
    steps:
      - name: Good bye world
        run: echo "Good bye world"
        shell: bash
